version: '3.8'
services:
  db:
    image: postgres:16
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass

  app:
    build: .
    depends_on:
      - db
    restart: on-failure # let Spring retry if the DB isn’t up yet
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
