# render.yaml
services:
  - type: web
    name: task-and-time-tracking-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerCommand: >
      java $JAVA_OPTS -Dspring.profiles.active=render -jar app.jar
    healthCheckPath: /actuator/health

databases:
  - name: task-time-management-db
    plan: free
