services:
  # Web service
  - type: web
    name: task-tracker
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerCommand: java $JAVA_OPTS -Dspring.profiles.active=render -jar app.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    healthCheckPath: /actuator/health

databases:
  - name: task-tracker-db
    plan: free